version: v1

labels:
  # Take a look at https://github.com/fuxingloh/multi-labeler
  # for more detailed documentation.

  - label: "ğŸ bug"
    matcher:
      title: "^fix:.*"
      body: "/fix"
      branch: "^fix/.*"
      commits: "^fix:.*"
    sync: true

  - label: "ğŸ—ï¸ ci"
    matcher:
      files:
        any: [".github/workflows/**/*.yml"]
    sync: true

  - label: "âœ¨ feature"
    matcher:
      title: "^feat:.*"
      body: "/feat"
      branch: "^feat/.*"
      commits: "^feat:.*"
    sync: true

  - label: ":octocat: github"
    matcher:
      files:
        any:
          [
            ".github/dependabot.yml",
            ".github/labels.yml",
            ".github/pull-request-labels.config.yml",
            ".github/workflows/**/*.yml",
          ]
    sync: true

  - label: "ğŸ›¸ github actions"
    matcher:
      files:
        any: [".github/workflows/**/*.yml"]
    sync: true
